- hosts: all
  tasks:
    - name: setup add-apt-repository
      become: yes
      when: ansible_os_family == "Debian"
      apt:
        name: software-properties-common
        state: present
    - include: playbooks/nvim.yml
