---
- hosts: all
  vars:
    nodejs_version: "7.x"
  tasks:
    - name: install ubuntu packages
      become: yes
      with_items:
        - silversearcher-ag
        - python
        - python-dev
        - ruby
      apt:
        name: "{{ item }}"
        state: present
    - name: setup add-apt-repository
      become: yes
      when: ansible_os_family == "Debian"
      apt:
        name: software-properties-common
        state: present
    - include: playbooks/nvim.yml
    - name: Symlink to windows directories
      become: no
      with_items:
        - Desktop
        - Documents
        - Pictures
      file:
        src: "/mnt/c/Users/micro/{{ item }}"
        dest: "{{ lookup('env','HOME') }}/{{ item }}"
        state: link
    - name: Symlink for git directory
      become: no
      file:
        src: "{{ lookup('env','HOME') }}/Documents/git"
        dest: "{{ lookup('env','HOME') }}/git"
        state: link
  roles:
    - role: geerlingguy.nodejs
    - role: jlund.ansible-go
    - role: laggyluke.direnv
