---
- hosts: all
  vars:
    nodejs_version: "7.x"
    windows_username: "micro"
    gitconfig_users:
      - user: halkeye
        name: Gavin Mogan
        email: git@gavinmogan.com
        ignore_github:
          - Linux
          - Vim
        ignore_custom: |
          .envrc
          *.bak
  tasks:
    - name: setup add-apt-repository
      become: yes
      when: ansible_os_family == "Debian"
      apt:
        name: software-properties-common
        state: present
    - include: playbooks/nvim.yml
    - include: playbooks/windowsdirs.yml
  roles:
    - role: geerlingguy.nodejs
    - role: jlund.ansible-go
    - role: laggyluke.direnv
    - role: mjanser.gitconfig
