---
- hosts: all
  tasks:
    - import_tasks: playbooks/tasks.yml
    - import_tasks: playbooks/fzf.yml
      tags:
        - fzf
    - import_tasks: playbooks/windowsdirs.yml
      when: windows_username is defined
    - import_tasks: playbooks/hub.yml
    - import_tasks: playbooks/vault.yml
      tags:
        - hashicorp
    - import_tasks: playbooks/genuinetools.yml
      tags:
        - genuinetools
    - import_tasks: playbooks/jump.yml
      tags:
        - jump
    - import_tasks: playbooks/directories.yml
      tags:
        - directories
    - import_tasks: playbooks/gnupg.yml
      tags:
        - gnupg
    - import_tasks: playbooks/wsl.yml
      when: "'wsl' in group_names"
      tags:
        - wsl
        - gnupg
  roles:

    - role: nvim
      tags:
        - nvim
    - role: ohmyposh
      tags:
        - ohmyposh
    - role: cimon-io.asdf
      tags:
        - asdf
    - role: zsh
      tags:
        - zsh
    - role: yogo1212.ansible-go
      tags:
        - golang
    - role: geerlingguy.git
      become: true
      when: ansible_os_family != "Darwin"
      tags:
        - git
    - role: carlba.gitconfig
      tags:
        - git
    - role: laggyluke.direnv
      tags:
        - direnv
    - role: tmux
      tags:
        - tmux
    - role: suzuki-shunsuke.tmux-tpm
      tags:
        - tmux
