---
- hosts: all
  tasks:
    - include: playbooks/tasks.yml
    - include: playbooks/nvim.yml
      tags:
        - nvim
    - include: playbooks/windowsdirs.yml
      when: windows_username is defined
    - include: playbooks/hub.yml
    - include: playbooks/tmux.yml
      tags:
        - tmux
    - include: playbooks/vault.yml
      tags:
        - hashicorp
    - include: playbooks/shell.yml
      tags:
        - zsh
    - include: playbooks/genuinetools.yml
      tags:
        - genuinetools
    - include: playbooks/directories.yml
      tags:
        - directories
    - include: playbooks/gnupg.yml
      tags:
        - gnupg
    - include: playbooks/wsl.yml
      when: "'wsl' in group_names"
      tags:
        - wsl
        - gnupg
  roles:
    - role: cimon-io.asdf
      tags:
        - asdf
    - role: yogo1212.ansible-go
      tags:
        - golang
    - role: geerlingguy.git
      when: ansible_os_family != "Darwin"
      tags:
        - git
    - role: laggyluke.direnv
      tags:
        - direnv
    - role: mjanser.gitconfig
    - role: suzuki-shunsuke.tmux-tpm
      tags:
        - tmux
    - role: geerlingguy.docker
      when: "'linux' in group_names"
    - role: cmprescott.chrome
      tags:
        - chrome
