---
- hosts: all
  tasks:

    - name: Gather package facts
      package_facts:
        manager: apt
      when: ansible_os_family == "Debian"

    - name: Accept Java 8 License
      become: yes
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: install ubuntu ppas
      become: yes
      with_items: "{{ global_ubuntu_ppas }}"
      when: ansible_os_family == "Debian"
      apt_repository:
        repo: "{{ item }}"
        state: present

    - name: install ubuntu packages
      become: yes
      when: ansible_os_family == "Debian"
      apt:
        name: "{{ global_ubuntu_packages }}"
        state: present
    - name: setup add-apt-repository
      become: yes
      when: ansible_os_family == "Debian"
      apt:
        name: software-properties-common
        state: present
    - include: playbooks/nvim.yml
      tags:
        - nvim
    - include: playbooks/windowsdirs.yml
      when: windows_username is defined
    - include: playbooks/hub.yml
#    - include: playbooks/telegram.yml
#      tags:
#        - telegram
#      when: "'linux' in group_names"
    - include: playbooks/tmux.yml
      tags:
        - tmux
    - include: playbooks/vault.yml
      tags:
        - hashicorp
    - include: playbooks/shell.yml
      tags:
        - zsh
    - include: playbooks/desktop.yml
      when: '"xserver-xorg" in ansible_facts.packages'
  roles:
    - role: viasite-ansible.zsh
      tags:
        - zsh
    - role: geerlingguy.nodejs
      tags:
        - nodejs
    - role: jlund.ansible-go
      tags:
        - golang
    - role: laggyluke.direnv
    - role: mjanser.gitconfig
    - role: suzuki-shunsuke.tmux-tpm
      tags:
        - tmux
    - role: gantsign.visual-studio-code
      when: "'linux' in group_names"
      users:
        - username: "{{ lookup('env','USER') }}"
          visual_studio_code_extensions:
            - Shan.code-settings-sync
          visual_studio_code_settings: {
            "sync.gist": "{{ vscode_config_gist }}"
          }
    - role: geerlingguy.docker
      when: "'linux' in group_names"
