---
- hosts: all
  tasks:
    - import_tasks: playbooks/tasks.yml
      tags:
        - software
    - import_tasks: playbooks/fzf.yml
      tags:
        - fzf
    - import_tasks: playbooks/genuinetools.yml
      tags:
        - genuinetools
    - import_tasks: playbooks/directories.yml
      tags:
        - directories
    - import_tasks: playbooks/vim.yml
      tags:
        - software
        - vim
    - import_tasks: playbooks/software.yml
      tags:
        - software
  roles:
    - role: halkeye.wsl
      when: "'wsl' in group_names"
      tags:
        - wsl
        - gnupg
    - role: ohmyposh
      ohmyposh_version: "{{ software_version_oh_my_posh }}"
      tags:
        - ohmyposh
        - shell
    - role: halkeye.asdf
      tags:
        - asdf
    - role: halkeye.nvim
      tags:
        - vim
        - software
    - role: halkeye.iamb
      tags:
        - iamb
        - software
    - role: zsh
      tags:
        - zsh
        - shell
    - role: yogo1212.ansible-go
      become: true
      tags:
        - golang
        - software
    - role: geerlingguy.git
      become: true
      when: ansible_os_family != "Darwin"
      tags:
        - git
    - role: tmux
      tags:
        - tmux
        - software
    - role: suzuki-shunsuke.tmux-tpm
      tags:
        - tmux
        - software
    - role: boutetnico.gitconfig
      tags:
        - git
      git_config_settings: "{{ global_git_config + group_git_config + host_git_config }}"
    - role: halkeye.sshconfig
      contents: "{{ ssh_config }}"
      home: "{{ env_home }}"
      owner: "{{ env_user }}"
      tags:
        - ssh
