---
- hosts: all
  pre_tasks:
    - import_tasks: playbooks/tasks.yml
      tags:
        - software
    - import_tasks: playbooks/fzf.yml
      tags:
        - fzf
    - import_tasks: playbooks/directories.yml
      tags:
        - directories
    - import_tasks: playbooks/software.yml
      tags:
        - software
  roles:
    - role: halkeye.wsl
      when: "'wsl' in group_names"
      tags:
        - wsl
        - gnupg
    - role: halkeye.ohmyposh
      ohmyposh_version: "{{ software_version_oh_my_posh }}"
      tags:
        - ohmyposh
        - shell
    - role: halkeye.asdf
      tags:
        - asdf
    - role: halkeye.nvim
      tags:
        - vim
        - software
    - role: halkeye.iamb
      tags:
        - iamb
        - software
    - role: halkeye.zsh
      tags:
        - zsh
        - shell
    - role: yogo1212.ansible-go
      become: true
      tags:
        - golang
        - software
    - role: geerlingguy.git
      become: true
      when: ansible_os_family != "Darwin"
      tags:
        - git
    - role: halkeye.tmux
      tags:
        - tmux
        - software
    - role: suzuki-shunsuke.tmux-tpm
      tags:
        - tmux
        - software
    - role: boutetnico.gitconfig
      tags:
        - git
      git_config_settings: "{{ global_git_config + group_git_config + host_git_config }}"
    - role: halkeye.sshconfig
      contents: "{{ ssh_config }}"
      home: "{{ env_home }}"
      owner: "{{ env_user }}"
      authorized_keys: "{{ global_authorized_keys }}"
      tags:
        - ssh
    - role: halkeye.ssh-to-age
      ssh_to_age_version: "{{ software_version_ssh_to_age }}"
      tags:
        - software
    - role: halkeye.krr
      krr_version: "{{ software_version_krr }}"
      tags:
        - software
    - role: halkeye.wezterm
      install: "'linux_desktop' in group_names"
      wezterm_version: "{{ software_version_wezterm }}"
      config_dir: "{{ wezterm_config_dir }}"
      tags:
        - wezterm
        - software
    - role: githubixx.kubectl
      become: true
      tags:
        - kubectl
        - software
    - role: halkeye.kubectl_krew
      krew_version: "v{{ software_version_krew }}"
      krew_plugins: "{{ krew_install_plugins }}"
      home: "{{ env_home }}"
      owner: "{{ env_user }}"
      tags:
        - software
        - kubectl
    - role: ctorgalson.nerdfonts
      when: nf_enabled
      tags:
        - fonts
    - role: halkeye.k9s
      tags:
        - software
        - k9s
      home: "{{ env_home }}"
      owner: "{{ env_user }}"
      k9s_version: "{{ software_version_k9s }}"
      architecture: "{{ deb_architecture }}"
    - role: halkeye.bat
      tags:
        - software
        - bat
      home: "{{ env_home }}"
      owner: "{{ env_user }}"
      bat_version: "{{ software_version_bat }}"
      architecture: "{{ deb_architecture }}"
