---
- hosts: all
  tasks:
    - import_tasks: playbooks/tasks.yml
    - import_tasks: playbooks/fzf.yml
      tags:
        - fzf
    - import_tasks: playbooks/windowsdirs.yml
      when: windows_username is defined
    - import_tasks: playbooks/genuinetools.yml
      tags:
        - genuinetools
    - import_tasks: playbooks/directories.yml
      tags:
        - directories
    - import_tasks: playbooks/vim.yml
      tags:
        - software
        - vim
    - import_tasks: playbooks/wsl.yml
      when: "'wsl' in group_names"
      tags:
        - wsl
        - gnupg
    - import_tasks: playbooks/software.yml
      tags:
        - software
    - import_tasks: playbooks/git_config.yml
      tags:
        - git
  roles:
    - role: ohmyposh
      tags:
        - ohmyposh
        - shell
    - role: halkeye.asdf
      tags:
        - asdf
    - role: halkeye.nvim
      tags:
        - vim
        - software
    - role: halkeye.iamb
      tags:
        - iamb
        - software
    - role: zsh
      tags:
        - zsh
        - shell
    - role: yogo1212.ansible-go
      become: true
      tags:
        - golang
        - software
    - role: geerlingguy.git
      become: true
      when: ansible_os_family != "Darwin"
      tags:
        - git
    - role: tmux
      tags:
        - tmux
        - software
    - role: suzuki-shunsuke.tmux-tpm
      tags:
        - tmux
        - software
