---
- hosts: all
  tasks:
    - name: install ubuntu packages
      become: yes
      with_items: "{{ global_ubuntu_packages }}"
      apt:
        name: "{{ item }}"
        state: present
    - name: setup add-apt-repository
      become: yes
      when: ansible_os_family == "Debian"
      apt:
        name: software-properties-common
        state: present
    - include: playbooks/nvim.yml
    - include: playbooks/windowsdirs.yml
      when: windows_username is defined
    - include: playbooks/hub.yml
    - include: playbooks/tmux.yml
      tags:
        - tmux
  roles:
    - role: geerlingguy.nodejs
    - role: jlund.ansible-go
    - role: laggyluke.direnv
    - role: mjanser.gitconfig
    - role: wtanaka.slack
