---
- hosts: all
  tasks:
    - include: playbooks/tasks.yml
    - include: playbooks/nvim.yml
      tags:
        - nvim
    - include: playbooks/hub.yml
    - include: playbooks/tmux.yml
      tags:
        - tmux
    - include: playbooks/vault.yml
      tags:
        - hashicorp
    - include: playbooks/shell.yml
      tags:
        - zsh
    - include: playbooks/desktop.yml
      when: '"xserver-xorg" in ansible_facts.packages'
    - include: playbooks/genuinetools.yml
      tags:
        - genuinetools
  roles:
    - role: geerlingguy.nodejs
      tags:
        - nodejs
    - role: ocha.yarn
      tags:
        - nodejs
    - role: geerlingguy.ruby
      tags:
        - ruby
    - role: yogo1212.ansible-go
      tags:
        - golang
    - role: geerlingguy.git
      tags:
        - git
    - role: laggyluke.direnv
    - role: mjanser.gitconfig
    - role: suzuki-shunsuke.tmux-tpm
      tags:
        - tmux
    - role: geerlingguy.docker
      when: "'linux' in group_names"

      #- role: comcast.sdkman

    - role: cimon-io.asdf
      tags:
        - asdf
    - role: cmprescott.chrome
      tags:
        - chrome
