roles:
  - name: yogo1212.ansible-go
    src: https://github.com/yogo1212/ansible-go
  - name: suzuki-shunsuke.tmux-tpm
    src: https://github.com/suzuki-shunsuke/ansible-tmux-tpm
  - name: geerlingguy.git
    src: https://github.com/geerlingguy/ansible-role-git
  - name: cimon-io.asdf
    src: https://github.com/eliberty/ansible-role-asdf
  - name: gikeymarcia.neovim
  - name: gantsign.helm
collections:
  - name: git+https://github.com/QueraTeam/ansible-github.git
