- name: geerlingguy.nodejs
- src: https://github.com/jlund/ansible-go
  name: jlund.ansible-go
- name: laggyluke.direnv
- name: mjanser.gitconfig
- name: wtanaka.slack
- name: gantsign.visual-studio-code
- name: viasite-ansible.zsh
