roles:
  - name: yogo1212.ansible-go
    src: https://github.com/yogo1212/ansible-go
  - name: suzuki-shunsuke.tmux-tpm
    src: https://github.com/suzuki-shunsuke/ansible-tmux-tpm
  - name: geerlingguy.git
    src: https://github.com/geerlingguy/ansible-role-git
  - name: cimon-io.asdf
    src: https://github.com/eliberty/ansible-role-asdf
    version: 762ebd2bd51b70db737873d10a081007460a5273
  - name: carlba.gitconfig
    src: https://github.com/carlba/ansible-role-gitconfig
  - name: breathe.release-from-github
    src: https://github.com/isometry/ansible-role-release-from-github
  - name: ansible-role-github-release
    src: https://github.com/ctorgalson/ansible-role-github-release
  - name: gikeymarcia.neovim
  - name: gantsign.helm
collections:
  - name: git+https://github.com/QueraTeam/ansible-github.git
