- name: geerlingguy.nodejs
  src: https://github.com/geerlingguy/ansible-role-nodejs
- name: geerlingguy.ruby
  src: https://github.com/geerlingguy/ansible-role-ruby
- name: jlund.ansible-go
  src: https://github.com/jlund/ansible-go
- name: laggyluke.direnv
  src: https://github.com/halkeye/ansible-role-direnv
- name: mjanser.gitconfig
  src: mjanser.gitconfig
- name: viasite-ansible.zsh
  src: https://github.com/viasite-ansible/ansible-role-zsh
- name: suzuki-shunsuke.tmux-tpm
  src: https://github.com/suzuki-shunsuke/ansible-tmux-tpm
- name: gantsign.visual-studio-code
  src: gantsign.visual-studio-code
- name: geerlingguy.docker
  src: geerlingguy.docker
- name: geerlingguy.git
  src: geerlingguy.git
- name: halkeye.ansible-docker-systemd
  src: https://github.com/halkeye/ansible-docker-systemd
- name: comcast.sdkman
  src: comcast.sdkman
- name: ocha.yarn
  src: ocha.yarn