- name: yogo1212.ansible-go
  src: https://github.com/yogo1212/ansible-go
- name: suzuki-shunsuke.tmux-tpm
  src: https://github.com/suzuki-shunsuke/ansible-tmux-tpm
- name: geerlingguy.git
  src: https://github.com/geerlingguy/ansible-role-git
- name: cimon-io.asdf
  src: https://github.com/eliberty/ansible-role-asdf
  ref: 762ebd2bd51b70db737873d10a081007460a5273
- name: carlba.gitconfig
  src: https://github.com/carlba/ansible-role-gitconfig
