- name: yogo1212.ansible-go
  src: https://github.com/yogo1212/ansible-go
- name: laggyluke.direnv
  src: https://github.com/halkeye/ansible-role-direnv
- name: suzuki-shunsuke.tmux-tpm
  src: https://github.com/suzuki-shunsuke/ansible-tmux-tpm
- name: geerlingguy.git
  src: https://github.com/geerlingguy/ansible-role-git
- name: cimon-io.asdf
  src: https://github.com/cimon-io/ansible-role-asdf
- name: carlba.gitconfig
  src: https://github.com/carlba/ansible-role-gitconfig
