- name: geerlingguy.nodejs
  src: https://github.com/geerlingguy/ansible-role-nodejs
- name: geerlingguy.ruby
  src: https://github.com/geerlingguy/ansible-role-ruby
- name: yogo1212.ansible-go
  src: https://github.com/yogo1212/ansible-go
- name: laggyluke.direnv
  src: https://github.com/halkeye/ansible-role-direnv
- name: mjanser.gitconfig
  src: https://github.com/mjanser/ansible-role-gitconfig
- name: suzuki-shunsuke.tmux-tpm
  src: https://github.com/suzuki-shunsuke/ansible-tmux-tpm
- name: geerlingguy.docker
  src: geerlingguy.docker
- name: geerlingguy.git
  src: geerlingguy.git
- name: halkeye.ansible-docker-systemd
  src: https://github.com/halkeye/ansible-docker-systemd
- name: cimon-io.asdf
  src: cimon-io.asdf
- name: ocha.yarn
  src: ocha.yarn
- name: cmprescott.chrome
  src: cmprescott.chrome
