- name: geerlingguy.nodejs
- src: https://github.com/jlund/ansible-go
  name: jlund.ansible-go
- src: https://github.com/halkeye/ansible-role-direnv
  name: laggyluke.direnv
- name: mjanser.gitconfig
- name: gantsign.visual-studio-code
- name: viasite-ansible.zsh
- name: suzuki-shunsuke.tmux-tpm
