roles:
  - name: yogo1212.ansible-go
    src: https://github.com/yogo1212/ansible-go
    version: 83006f3078b6910465eeecd1ebdc791ad6684b06
  - name: suzuki-shunsuke.tmux-tpm
    src: https://github.com/suzuki-shunsuke/ansible-tmux-tpm
  - name: geerlingguy.git
    src: https://github.com/geerlingguy/ansible-role-git
    version: 3.0.1
  - name: cimon-io.asdf
    src: https://github.com/eliberty/ansible-role-asdf
    version: 762ebd2bd51b70db737873d10a081007460a5273
  - name: gikeymarcia.neovim
  - name: gantsign.helm
collections:
  - name: git+https://github.com/QueraTeam/ansible-github.git
