---
- name: Copy all the default asdf files into home dir
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ env_home }}/.{{ item }}"
    owner: "{{ env_user }}"
    mode: '0644'
  with_items:
    - default-gems
    - default-npm-packages
    - default-python-packages
    - default-perl-modules

- name: Configure asdf
  ansible.builtin.include_role:
    name: cimon-io.asdf
