---
- name: Copy all the default asdf files into home dir
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ env_home }}/.{{ item }}"
    owner: "{{ env_user }}"
    mode: '0644'
  with_items:
    - default-gems
    - default-npm-packages
    - default-python-packages
    - default-perl-modules
    - asdfrc

- name: Ensure global tool versions exists
  ansible.builtin.file:
    path: "{{ env_home }}/.tool-versions"
    state: touch
    owner: "{{ env_user }}"
    mode: '0644'

- name: Ensure global tool versions
  ansible.builtin.lineinfile:
    path: "{{ env_home }}/.tool-versions"
    regexp: '^{{ item.name }}'
    line: "{{ item.name }} {{ item.global }}"
    owner: "{{ env_user }}"
    mode: '0644'
  with_items: "{{ asdf_plugins }}"

- name: Install asdf
  become: true
  quera.github.install_from_github:
    repo: asdf-vm/asdf
    tag: "{{ software_version_asdf }}"
    version_command: asdf version
    asset_regex: asdf-.*-linux-.*.tar.gz
    move_rules:
      - src_regex: asdf
        dst: /usr/local/bin/asdf
        mode: 0755

- name: Make sure plugins are installed
  ansible.builtin.command: "asdf plugin add {{item.name}}"
  with_items: "{{ asdf_plugins }}"

- name: Make sure default global stuff is installed
  ansible.builtin.command:
    cmd: "asdf install {{ item.name }}"
    chdir: "{{ env_home }}"
  ignore_errors: true
  with_items: "{{ asdf_plugins }}"
