---
- name: Install tmux
  become: true
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name:
      - tmux
    state: present

- name: Install tmux.conf
  ansible.builtin.template:
    src: templates/tmux.conf.j2
    dest: "{{ env_home }}/.tmux.conf"
    mode: "0644"
    owner: "{{ env_user }}"

- name: Copy tmux-session to bin
  become: true
  ansible.builtin.copy:
    src: "tmux-session"
    dest: "/usr/local/bin/tmux-session"
    owner: "root"
    mode: '0755'
