---
- name: Create .ssh directory
  ansible.builtin.file:
    path: "{{ home }}/.ssh"
    state: directory
    mode: "0755"

- name: Create ssh config
  ansible.builtin.copy:
    dest: "{{ home }}/.ssh/config"
    owner: "{{ owner }}"
    mode: "0700"
    content: "{{ contents }}"
