---
- name: Create config directory
  become: false
  ansible.builtin.file:
    path: "{{ env_home }}/.config"
    state: directory
    mode: "0755"

- name: Create config k9s directory
  become: false
  ansible.builtin.file:
    path: "{{ env_home }}/.config/k9s"
    state: directory
    mode: "0755"

- name: Create config k9s skins directory
  become: false
  ansible.builtin.file:
    path: "{{ env_home }}/.config/k9s/skins"
    state: directory
    mode: "0755"

- name: Download catppuccin-mocha
  become: false
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/catppuccin/k9s/fdbec82284744a1fc2eb3e2d24cb92ef87ffb8b4/dist/catppuccin-mocha.yaml
    dest: '{{ env_home }}/.config/k9s/skins/catppuccin-mocha.yaml'
    mode: '0600'

- name: Open yaml file
  slurp:
    path: '{{ env_home }}/.config/k9s/config.yaml'
  register: r_k9s_config

- name: Read yaml to dictionary
  set_fact:
    k9sconfig: "{{ r_k9s_config['content'] | b64decode | from_yaml }}"

- name: Override skin
  set_fact:
    k9sconfig: "{{ k9sconfig | combine(newdata, recursive=True) }}"
  vars: 
    newdata:
      k9s:
        ui:
          skin: catppuccin-mocha

- name: Write config.yaml file
  copy:
    content: '{{ k9sconfig | to_nice_yaml }}'
    dest: '{{ env_home }}/.config/k9s/config.yaml'


- name: Download debs
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/derailed/k9s/releases/download/v{{ k9s_version }}/k9s_linux_{{ architecture }}.deb"
    dest: /var/cache/apt/archives/k9s-{{ k9s_version }}.deb
    mode: '0600'

- name: Install package
  become: true
  ansible.builtin.apt:
    deb: /var/cache/apt/archives/k9s-{{ k9s_version }}.deb
