---
- name: Create config k9s directory
  become: false
  ansible.builtin.file:
    path: "{{ env_home }}/.config/k9s"
    recurse: true
    state: directory
    mode: "0755"

- name: Create config k9s skins directory
  become: false
  ansible.builtin.file:
    path: "{{ env_home }}/.config/k9s/skins"
    state: directory
    mode: "0755"

- name: Download catppuccin-mocha
  become: false
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/catppuccin/k9s/fdbec82284744a1fc2eb3e2d24cb92ef87ffb8b4/dist/catppuccin-mocha.yaml
    dest: '{{ env_home }}/.config/k9s/skins/catppuccin-mocha.yaml'
    mode: '0600'

- name: Make sure config file exists
  become: false
  ansible.builtin.file:
    path: '{{ env_home }}/.config/k9s/config.yaml'
    state: touch
    modification_time: preserve
    access_time: preserve
    mode: "0755"

- name: Open config.yaml file
  slurp:
    path: '{{ env_home }}/.config/k9s/config.yaml'
  register: r_k9s_config

# - name: Read config.yaml to dictionary
#   set_fact:
#     k9sconfig: "{{ r_k9s_config['content'] | b64decode | from_yaml }}"

- name: Override skin
  set_fact:
    k9sconfig: "{{ r_k9s_config['content'] | b64decode | from_yaml  | combine(newdata, recursive=True) }}"
  vars: 
    newdata:
      k9s:
        ui:
          skin: catppuccin-mocha

- name: Write config.yaml file
  copy:
    content: '{{ k9sconfig | to_nice_yaml }}'
    dest: '{{ env_home }}/.config/k9s/config.yaml'

- name: Install package
  become: true
  ansible.builtin.apt:
    name: k9s
