---
- name: install zsh
  become: true
  when: ansible_os_family == "Debian"
  apt:
    name:
      - zsh
    state: present

- name: change user shell to zsh
  become: true
  when: "'ldap' not in group_names"
  user:
    name: "{{ env_user }}"
    shell: /bin/zsh

- name: install .zshrc
  copy:
    src: zshrc
    remote_src: false
    dest: "{{ env_home }}/.zshrc"
    owner: "{{ env_user }}"
    mode: 0700
