---
- name: Setup architecture map
  ansible.builtin.set_fact:
    deb_architectures: { "armv6l": "armhf", "armv7l": "armhf", "aarch64": "arm64", "x86_64": "amd64", "i386": "i386" } 

- name: Setup architecture variable (if not already set)
  ansible.builtin.set_fact:
    ohmyposh_arch: "{{ [ansible_architecture] | map('extract', deb_architectures) | first }}"
    ohmyposh_os: linux
  when: (ohmyposh_arch is not defined)

- name: Check if oh-my-posh is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/oh-my-posh
  register: ohmyposh_already_installed

- name: Fetch installed oh-my-posh version
  ansible.builtin.command: "/usr/local/bin/oh-my-posh --version"
  register: results
  when: ohmyposh_already_installed.stat.exists
  changed_when: results.rc != 0

- name: Process oh-my-posh version
  ansible.builtin.set_fact:
    ohmyposh_installed_version: "{{ results.stdout | trim }}"
  when: ohmyposh_already_installed.stat.exists and results.stdout | trim

- name: Download and install oh-my-posh
  become: true
  when: ohmyposh_installed_version != ohmyposh_version
  ansible.builtin.get_url:
    force: true
    url: "https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v{{ ohmyposh_version }}/posh-{{ ansible_system | lower }}-{{ ohmyposh_arch }}"
    dest: /usr/local/bin/oh-my-posh
    mode: '0755'

- name: Create oh-my-post theme directory
  become: false
  ansible.builtin.file:
    path: "{{ ohmyposh_theme_directory }}"
    state: directory
    mode: "0755"

- name: Extract oh-my-posh-themes
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v{{ ohmyposh_version }}/themes.zip"
    remote_src: true
    dest: "{{ ohmyposh_theme_directory }}"
    mode: "0755"

- name: Find files
  ansible.builtin.find:
    paths: "{{ ohmyposh_theme_directory }}"
    patterns: "*.omp.*"
  register: omp_files

- name: Modify the file permissions
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: "0755"
  with_items: "{{ omp_files.files }}"
  when:
    - item.mode != "0755"
