---
- name: install tmux
  become: true
  when: ansible_os_family == "Debian"
  apt:
    name:
      - tmux
    state: present

- name: "Install tmux.conf"
  template:
    src: templates/tmux.conf.j2
    dest: "{{ env_home }}/.tmux.conf"
    mode: 0644
    owner: "{{ env_user }}"

- name: "copy tmux-session to bin"
  become: true
  copy:
    src: "tmux-session"
    dest: "/usr/local/bin/tmux-session"
    owner: "root"
    mode: '0755'
