---
- become: yes
  when: ansible_os_family == "Debian"
  apt:
    name:
      - fzf
    state: absent

- name: Download fzf from git
  become: no
  git:
    repo: "https://github.com/junegunn/fzf.git"
    dest: "{{ env_home }}/.fzf"
    version: "0.24.2"

- name: Run install script
  ansible.builtin.command: "{{ env_home }}/.fzf/install --no-update-rc"
  args:
    creates: "{{ env_home }}/.fzf/bin/fzf"
