---
- become: true
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name:
      - fzf
    state: absent

- name: Download fzf from git
  become: false
  ansible.builtin.git:
    repo: "https://github.com/junegunn/fzf.git"
    dest: "{{ env_home }}/.fzf"
    version: "{{ software_version_fzf }}"

- name: "Check if fzf is already installed"
  ansible.builtin.stat:
    path: "{{ env_home }}/.fzf/bin/fzf"
  register: fzf_already_installed

- name: "Fetch installed fzf version"
  ansible.builtin.command: "{{ env_home }}/.fzf/bin/fzf --version"
  register: results
  when: fzf_already_installed.stat.exists

- name: "Process fzf version"
  ansible.builtin.set_fact:
    fzf_installed_version: "{{ results.stdout | trim | regex_replace('([a-z0-9A-Z._-]+).*','\\1') }}"
  when: fzf_already_installed.stat.exists and (results.stdout | trim)

- name: Run install script
  ansible.builtin.command: "{{ env_home }}/.fzf/install --no-update-rc"
  when: fzf_installed_version is not defined or (fzf_installed_version != software_version_fzf)
  #args:
  #  creates: "{{ env_home }}/.fzf/bin/fzf"

