---
- name: install required packages
  become: yes
  when: ansible_os_family == "Debian"
  apt:
    name:
      - gpg-agent 
      - gpg-wks-server
      - gpg-wks-client
      - gnupg
    state: present

- name: Ensure .gnupg directory is created
  file:
    dest: "{{ env_home }}/.gnupg"
    state: directory
    owner: "{{ env_user }}"
    mode: 0700

- name: Create gpg-agent.conf
  copy:
    src: ./gnupg/gpg-agent.conf
    remote_src: false
    dest: "{{ env_home }}/.gnupg/gpg-agent.conf"
    mode: 0644
    owner: "{{ env_user }}"