- name: remove old neovim ppa
  become: yes
  when: ansible_os_family == "Debian"
  apt_repository:
    repo: "ppa:neovim-ppa/stable"
    state: absent
- name: setup neovim ppa
  become: yes
  when: ansible_os_family == "Debian"
  apt_repository:
    repo: "ppa:neovim-ppa/unstable"
    state: present
- name: setup neovim
  become: yes
  when: ansible_os_family == "Debian"
  apt:
    name:
      - neovim
      - python3-neovim
      - python-neovim
      - ctags
    state: present
- name: setup neovim
  become: yes
  pip:
    name:
      - pynvim
    state: present
- name: setup neovim
  become: yes
  gem:
    name:
      - neovim
    state: present
- name: setup neovim alternatives
  become: yes
  when: ansible_os_family == "Debian"
  with_items:
    - vi
    - vim
    - editor
  alternatives:
    link: "/usr/bin/{{ item }}"
    name: "{{ item }}"
    path: "/usr/bin/nvim"
    priority: 60
- name: Download config from git
  become: no
  git:
    repo: 'git@github.com:halkeye/vim.git'
    dest: "{{ lookup('env','HOME') }}/.vim"
- name: Create config directory
  become: no
  file:
    path: "{{ lookup('env','HOME') }}/.config"
    state: directory
- name: Symlink for neovim config
  become: no
  file:
    src: "{{ lookup('env','HOME') }}/.vim"
    dest: "{{ lookup('env','HOME') }}/.config/nvim"
    state: link
- name: Install vundle
  become: no
  shell: "./install_vundle.sh"
  args:
    chdir: "{{ lookup('env','HOME') }}/.vim"
    creates: "bundle/Vundle.vim"
- name: Install Plugins
  become: no
  shell: "nvim -E -s -c 'source ~/.vimrc' -c PluginInstall -c qa"
  register: vim_plugin_install_cmd
  failed_when: vim_plugin_install_cmd.rc == 1 or vim_plugin_install_cmd.rc >= 2
  args:
    chdir: "{{ lookup('env','HOME') }}/.vim"
