---
- name: install zsh
  become: yes
  when: ansible_os_family == "Debian"
  apt:
    name:
      - zsh
    state: present

- name: Get DEB architecture
  shell: "bash -c 'if [ \"$(arch)\" == \"x86_64\" ]; then echo amd64; else arch; fi'"
  register: deb_architecture

- name: Download and install powerline-go
  command: "bash -c '/usr/local/go/bin/go get github.com/justjanne/powerline-go'"
  become: true
  become_user: "{{ env_user }}"
  args:
    creates: "{{ env_home }}/go/bin/powerline-go"

- name: Update bashrc
  when: "'wsl' in group_names"
  blockinfile:
    dest: "{{ env_home }}/.bashrc"
    block: |
      if [ -t 1 ]; then exec zsh;fi

- name: install .zshrc
  copy:
    src: ./shell/zshrc
    remote_src: false
    dest: "{{ env_home }}/.zshrc"
    group: "{{ env_user }}"
    owner: "{{ env_user }}"
    mode: 0700
