---
- name: Update bashrc
  when: "'wsl' in group_names"
  blockinfile:
    dest: "{{ lookup('env','HOME') }}/.bashrc"
    block: |
      if [ -t 1 ]; then exec zsh;fi

- name: ensure .zshrc.local exists
  file:
    path: "{{ lookup('env','HOME') }}/.zshrc.local"
    group: "{{ lookup('env', 'USER') }}"
    owner: "{{ lookup('env', 'USER') }}"
    mode: 0700
    state: "touch"

- name: Add timezone to .zshrc.local
  blockinfile:
    dest: "{{ lookup('env','HOME') }}/.zshrc.local"
    block: |
      export POWERLEVEL9K_TIME_FORMAT='%D{\%I:\%M:\%S \%p}'
      export TZ=America/Vancouver
      if [ -e "$HOME/bin" ]; then export PATH="$HOME/bin:$PATH"; fi
      alias ag="ag --color-path 35 --color-match '1;35' --color-line-number 32"
      alias webbie="python -m SimpleHTTPServer"
      #alias ncu="npx -p npm-check-updates ncu"
      alias ncu="docker run -it --rm -v $(pwd)/package.json:/app/package.json creack/ncu"

- name: Make sure wsl don't use fzf for history search
  blockinfile:
    dest: "{{ lookup('env','HOME') }}/.zshrc.local"
    marker: "# {mark} SECOND ANSIBLE MANAGED BLOCK"
    block: |
      bindkey "^R" history-incremental-search-backward
  when: "'wsl' in group_names"
