---
- name: Get DEB architecture
  shell: "bash -c 'if [ \"$(arch)\" == \"x86_64\" ]; then echo amd64; else arch; fi'"
  register: deb_architecture

- name: Download and install powerline-go
  get_url:
    url: "https://github.com/justjanne/powerline-go/releases/download/v1.15.0/powerline-go-linux-{{ deb_architecture.stdout }}"
    dest: /usr/bin/powerline-go
    mode: '0755'

- name: Update bashrc
  when: "'wsl' in group_names"
  blockinfile:
    dest: "{{ lookup('env','HOME') }}/.bashrc"
    block: |
      if [ -t 1 ]; then exec zsh;fi

- template:
    src: templates/zshrc.j2
    dest: "{{ lookup('env','HOME') }}/.zshrc"
    group: "{{ lookup('env', 'USER') }}"
    owner: "{{ lookup('env', 'USER') }}"
    mode: 0700
