---
- name: Update bashrc
  when: "'wsl' in group_names"
  blockinfile:
    dest: "{{ lookup('env','HOME') }}/.bashrc"
    block: |
      if [ -t 1 ]; then exec zsh;fi

- template:
    src: templates/zshrc.j2
    dest: "{{ lookup('env','HOME') }}/.zshrc"
    group: "{{ lookup('env', 'USER') }}"
    owner: "{{ lookup('env', 'USER') }}"
    mode: 0700

