---
- name: install zsh
  become: yes
  when: ansible_os_family == "Debian"
  apt:
    name:
      - zsh
    state: present

- name: change user shell to zsh
  become: yes
  when: "'ldap' not in group_names"
  user:
    name: "{{ env_user }}"
    shell: /bin/zsh

- name: Download and install powerline-go
  command: "bash -c '/usr/local/go/bin/go install github.com/justjanne/powerline-go@v1.21.0'"
  become: true
  become_user: "{{ env_user }}"
  args:
    creates: "{{ env_home }}/go/bin/powerline-go"

- name: install .zshrc
  copy:
    src: ./shell/zshrc
    remote_src: false
    dest: "{{ env_home }}/.zshrc"
    owner: "{{ env_user }}"
    mode: 0700
