---
# sops
- name: install latest version of helm
  ansible.builtin.include_role:
    name: gantsign.helm
    apply:
      become: yes
  vars:
    helm_version: "{{ software_version_helm }}"

# Start Debs

- name: Create list of debs
  ansible.builtin.set_fact:
    software_debs:
      - { url: "https://github.com/ajeetdsouza/zoxide/releases/download/v{{software_version_zoxide}}/zoxide_{{software_version_zoxide}}-1_amd64.deb", "name": "zoxide", "version": "{{software_version_zoxide}}" }
      - { url: "https://github.com/sharkdp/bat/releases/download/v{{software_version_bat}}/bat_{{software_version_bat}}_amd64.deb", "name": "bat", "version": "{{software_version_bat}}" }
      - { url: "https://github.com/lsd-rs/lsd/releases/download/v{{software_version_lsd}}/lsd_{{software_version_lsd}}_amd64.deb", "name": "lsd", "version": "{{software_version_lsd}}" }
      - { url: "https://github.com/derailed/k9s/releases/download/v{{software_version_k9s}}/k9s_linux_amd64.deb", "name": "k9s", "version": "{{software_version_k9s}}" }
      - { url: "https://github.com/cli/cli/releases/download/v{{software_version_gh}}/gh_{{software_version_gh}}_linux_amd64.deb", "name": "gh", "version": "{{software_version_gh}}" }
      - { url: "https://github.com/sharkdp/fd/releases/download/v10.1.0/fd_{{software_version_fd}}_amd64.deb", "name": "fd", "version": "{{software_version_fd}}" }
      - { url: "https://github.com/BurntSushi/ripgrep/releases/download/{{software_version_ripgrep}}/ripgrep_{{software_version_ripgrep}}-1_amd64.deb", "name": "ripgrep", "version": "{{software_version_ripgrep}}" }

- name: Download debs
  become: yes
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: /var/cache/apt/archives/{{ item.name }}-{{ item.version }}.deb
    mode: '0600'
  with_items: "{{ software_debs }}"

- name: Install package
  become: yes
  ansible.builtin.apt:
    deb: /var/cache/apt/archives/{{ item.name }}-{{ item.version }}.deb
  with_items: "{{ software_debs }}"

# Done Debs

- name: install age
  become: yes
  quera.github.install_from_github:
    repo: FiloSottile/age
    tag: "v{{software_version_age}}"
    version_command: age --version
    asset_regex: "age-.*"
    move_rules:
      - src_regex: age-.*
        dst: /usr/local/bin/age
        mode: 0755

- name: install fx
  become: yes
  quera.github.install_from_github:
    repo: antonmedv/fx
    tag: "{{software_version_fx}}"
    version_command: fx --version
    asset_regex: fx_.*
    move_rules:
      - src_regex: fx_.*
        dst: /usr/local/bin/fx
        mode: 0755

- name: install doctl
  become: yes
  quera.github.install_from_github:
    repo: digitalocean/doctl
    tag: "v{{software_version_doctl}}"
    version_command: doctl version
    asset_regex: doctl.*
    move_rules:
      - src_regex: doctl.*
        dst: /usr/local/bin/doctl
        mode: 0755

- name: install helmfile
  become: yes
  quera.github.install_from_github:
    repo: helmfile/helmfile
    tag: "v{{software_version_helmfile}}"
    version_command: helmfile --version
    asset_regex: helmfile.*
    move_rules:
      - src_regex: helmfile.*
        dst: /usr/local/bin/helmfile
        mode: 0755

- name: install kubectx
  become: yes
  quera.github.install_from_github:
    repo: ahmetb/kubectx
    tag: "v{{software_version_kubectx}}"
    version_command: kubectx --version
    asset_regex: kubectx.*
    move_rules:
      - src_regex: kubectx.*
        dst: /usr/local/bin/kubectx
        mode: 0755

- name: install shellcheck
  become: yes
  quera.github.install_from_github:
    repo: koalaman/shellcheck
    tag: "v{{software_version_shellcheck}}"
    version_command: shellcheck --version
    asset_regex: shellcheck.*
    move_rules:
      - src_regex: shellcheck
        dst: /usr/local/bin/shellcheck
        mode: 0755

- name: install hadolint
  become: yes
  quera.github.install_from_github:
    repo: hadolint/hadolint
    tag: "v{{software_version_hadolint}}"
    version_command: hadolint --version
    asset_regex: hadolint.*
    move_rules:
      - src_regex: hadolint.*
        dst: /usr/local/bin/hadolint
        mode: 0755

- name: install oh_my_posh
  become: yes
  quera.github.install_from_github:
    repo: JanDeDobbeleer/oh-my-posh
    tag: "v{{software_version_oh_my_posh}}"
    version_command: oh_my_posh --version
    asset_regex: posh-\w+-\w+
    move_rules:
      - src_regex: posh.*
        dst: /usr/local/bin/oh_my_posh
        mode: 0755

- name: install win32yank
  become: yes
  when: "'wsl' in group_names"
  quera.github.install_from_github:
    repo: equalsraf/win32yank
    tag: "v{{software_version_win32yank}}"
    version_command: win32yank --version
    asset_regex: win32yank-x86
    move_rules:
      - src_regex: win32yank.*
        dst: /usr/local/bin/win32yank
        mode: 0755

- name: install typos
  become: yes
  quera.github.install_from_github:
    repo: crate-ci/typos
    tag: "v{{software_version_typos}}"
    version_command: typos --version
    asset_regex: typos.*
    move_rules:
      - src_regex: typos.*
        dst: /usr/local/bin/typos
        mode: 0755
