---
- name: install tmux
  become: yes
  when: ansible_os_family == "Debian"
  apt:
    name:
      - tmux
      - tmuxinator
    state: present
- template:
    src: templates/tmux.conf.j2
    dest: "{{ env_home }}/.tmux.conf"
    mode: 0644
    owner: "{{ env_user }}"
