---
- name: install required packages
  become: yes
  when: ansible_os_family == "Debian"
  apt:
    name:
      - socat
    state: present

- name: Download xdg_open_wsl.py
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/cpbotha/xdg-open-wsl/1156fe54344e35cf763b65c129df868647e455de/xdg_open_wsl/xdg_open_wsl.py
    dest: /usr/local/bin/xdg-open
    mode: '0755'

- name: Download pinentry-wsl-ps1
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/diablodale/pinentry-wsl-ps1/master/pinentry-wsl-ps1.sh
    dest: /usr/local/bin/pinentry-wsl-ps1
    mode: '0755'

- name: Set gpg-agent.conf's pinentry-program to pinentry-wsl-ps1
  lineinfile:
    dest: "{{ env_home }}/.gnupg/gpg-agent.conf"
    regexp: 'pinentry-program'
    line: "enable-putty-support /usr/local/bin/pinentry-wsl-ps1"

- name: Enable enable-putty-support in windows exists
  file:
    dest: "/mnt/c/Users/{{ windows_username }}/AppData/Roaming/gnupg/gpg-agent.conf"
    state: touch

- name: Enable enable-putty-support in windows gpg-agent.conf
  lineinfile:
    dest: "/mnt/c/Users/{{ windows_username }}/AppData/Roaming/gnupg/gpg-agent.conf"
    regexp: 'enable-putty-support'
    line: enable-putty-support

- name: create npiperelay
  become: true
  file:
    path: "/mnt/c/Users/{{ windows_username }}/AppData/Roaming/npiperelay"
    state: directory
    mode: 0700

- name: Download npiperelay.exe
  become: true
  get_url:
    url: https://github.com/NZSmartie/npiperelay/releases/download/v0.1/npiperelay.exe
    dest: "/mnt/c/Users/{{ windows_username }}/AppData/Roaming/npiperelay/npiperelay.exe"
    mode: '777'

- name: create wsl-ssh-pageant
  become: true
  file:
    path: "/mnt/c/Users/{{ windows_username }}/AppData/Roaming/wsl-ssh-pageant"
    state: directory
    mode: 0700

- name: Download wsl-ssh-pageant.exe
  become: true
  get_url:
    url: https://github.com/benpye/wsl-ssh-pageant/releases/download/20200408.1/wsl-ssh-pageant-amd64-gui.exe
    dest: "/mnt/c/Users/{{ windows_username }}/AppData/Roaming/wsl-ssh-pageant/wsl-ssh-pageant-amd64-gui.exe"
    mode: '777'

- name: install gpg-agent-relay
  copy:
    src: ./wsl/gpg-agent-relay
    remote_src: false
    dest: "/usr/local/bin/gpg-agent-relay"
    mode: 0755

#https://blog.nimamoh.net/yubi-key-gpg-wsl2/