---
- name: install required packages
  become: yes
  when: ansible_os_family == "Debian"
  apt:
    name:
      - socat
      - wslu
    state: present

- name: Download xdg_open_wsl.py
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/cpbotha/xdg-open-wsl/1156fe54344e35cf763b65c129df868647e455de/xdg_open_wsl/xdg_open_wsl.py
    dest: /usr/local/bin/xdg-open
    mode: '0755'

