---
- name: install required packages
  become: yes
  when: ansible_os_family == "Debian"
  apt:
    name:
      - socat
      - wslu
    state: present

- name: Remove local xdg-open
  become: yes
  file:
    state: absent
    path: /usr/local/bin/xdg-open

- name: Map wslview to xdg-open
  become: yes
  file:
    state: link
    src: /usr/bin/wslview
    dest: /usr/bin/xdg-open
